// <auto-generated />
using System;
using AIEnabledRma.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AIEnabledRma.Data.Migrations
{
    [DbContext(typeof(RmaDbContext))]
    [Migration("20260930031144_AddRmaExclusions")]
    partial class AddRmaExclusions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIEnabledRma.Domain.Catalog.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("firmware_version");

                    b.Property<string>("HardwareRevision")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hardware_revision");

                    b.Property<string>("Imei")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("imei");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mac_address");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ReplacementForSerialNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("replacement_for_serial_number");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("serial_number");

                    b.Property<DateTimeOffset?>("ShippedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shipped_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_devices_product_id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_devices_serial");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Catalog.DeviceAlternateIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("identifier");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.HasKey("Id")
                        .HasName("pk_device_alternate_identifiers");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_alternate_identifiers_device_id");

                    b.HasIndex("Identifier")
                        .HasDatabaseName("ix_device_alt_identifier");

                    b.ToTable("device_alternate_identifiers", (string)null);
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsMerchandise")
                        .HasColumnType("boolean")
                        .HasColumnName("is_merchandise");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_products_sku");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Catalog.Warranty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("plan_name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("pk_warranties");

                    b.HasIndex("DeviceId", "EndDate")
                        .HasDatabaseName("ix_warranty_device_end");

                    b.ToTable("warranties", (string)null);
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Customers.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("country_code")
                        .IsFixedLength();

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("label");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("line2");

                    b.Property<string>("Line3")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("line3");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("postal_code");

                    b.Property<string>("StateOrProvince")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("state_or_province");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_addresses_customer");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("company_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailOptIn")
                        .HasColumnType("boolean")
                        .HasColumnName("email_opt_in");

                    b.Property<string>("ExternalCustomerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_customer_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("middle_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("SecondaryEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("secondary_email");

                    b.Property<string>("TaxId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_customers_email");

                    b.HasIndex("ExternalCustomerId")
                        .HasDatabaseName("ix_customers_external_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Rma.RmaExclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Eligibility")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("eligibility");

                    b.Property<string>("Explanation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explanation");

                    b.Property<string>("MatchedOn")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("matched_on");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RmaRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("rma_request_id");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("serial_number");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_rma_exclusions");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_rma_exclusions_device_id");

                    b.HasIndex("RmaRequestId")
                        .HasDatabaseName("ix_rma_exclusions_request");

                    b.ToTable("rma_exclusions", (string)null);
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Rma.RmaLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ProblemCategoryCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("problem_category_code");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("problem_description");

                    b.Property<string>("RecommendedStepsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("recommended_steps_json");

                    b.Property<Guid>("RmaRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("rma_request_id");

                    b.Property<string>("TriageArticleIds")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("triage_article_ids");

                    b.Property<double?>("TriageConfidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("triage_confidence");

                    b.Property<string>("TriageVerdict")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("triage_verdict");

                    b.Property<string>("WhatCustomerTried")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("what_customer_tried");

                    b.HasKey("Id")
                        .HasName("pk_rma_lines");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_rma_lines_device");

                    b.HasIndex("RmaRequestId")
                        .HasDatabaseName("ix_rma_lines_rma_request_id");

                    b.ToTable("rma_lines", (string)null);
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Rma.RmaRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DepositAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("deposit_amount");

                    b.Property<string>("EligibilityReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("eligibility_reason");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payment_transaction_id");

                    b.Property<string>("PolicyRuleTrace")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("policy_rule_trace");

                    b.Property<string>("RmaNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rma_number");

                    b.Property<Guid?>("ShipToAddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("ship_to_address_id");

                    b.Property<decimal>("ShippingCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("shipping_charge");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TroubleshootingSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("troubleshooting_summary");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WarrantyTier")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("warranty_tier");

                    b.HasKey("Id")
                        .HasName("pk_rma_requests");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_rma_requests_customer_id");

                    b.HasIndex("RmaNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_rma_requests_number");

                    b.HasIndex("ShipToAddressId")
                        .HasDatabaseName("ix_rma_requests_ship_to_address_id");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_rma_status_created");

                    b.ToTable("rma_requests", (string)null);
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Catalog.Device", b =>
                {
                    b.HasOne("AIEnabledRma.Domain.Catalog.Product", "Product")
                        .WithMany("Devices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Catalog.DeviceAlternateIdentifier", b =>
                {
                    b.HasOne("AIEnabledRma.Domain.Catalog.Device", "Device")
                        .WithMany("AlternateIdentifiers")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_alternate_identifiers_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Catalog.Warranty", b =>
                {
                    b.HasOne("AIEnabledRma.Domain.Catalog.Device", "Device")
                        .WithMany("Warranties")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_warranties_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Customers.Address", b =>
                {
                    b.HasOne("AIEnabledRma.Domain.Customers.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_addresses_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Rma.RmaExclusion", b =>
                {
                    b.HasOne("AIEnabledRma.Domain.Catalog.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_rma_exclusions_devices_device_id");

                    b.HasOne("AIEnabledRma.Domain.Rma.RmaRequest", "RmaRequest")
                        .WithMany("Exclusions")
                        .HasForeignKey("RmaRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rma_exclusions_rma_requests_rma_request_id");

                    b.Navigation("Device");

                    b.Navigation("RmaRequest");
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Rma.RmaLine", b =>
                {
                    b.HasOne("AIEnabledRma.Domain.Catalog.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rma_lines_devices_device_id");

                    b.HasOne("AIEnabledRma.Domain.Rma.RmaRequest", "RmaRequest")
                        .WithMany("Lines")
                        .HasForeignKey("RmaRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rma_lines_rma_requests_rma_request_id");

                    b.Navigation("Device");

                    b.Navigation("RmaRequest");
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Rma.RmaRequest", b =>
                {
                    b.HasOne("AIEnabledRma.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rma_requests_customers_customer_id");

                    b.HasOne("AIEnabledRma.Domain.Customers.Address", "ShipToAddress")
                        .WithMany()
                        .HasForeignKey("ShipToAddressId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rma_requests_addresses_ship_to_address_id");

                    b.Navigation("Customer");

                    b.Navigation("ShipToAddress");
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Catalog.Device", b =>
                {
                    b.Navigation("AlternateIdentifiers");

                    b.Navigation("Warranties");
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Catalog.Product", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Customers.Customer", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("AIEnabledRma.Domain.Rma.RmaRequest", b =>
                {
                    b.Navigation("Exclusions");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
